spring:
  profiles:
    active:
      - dev
---
server:
  port: 8101

spring:
  profiles: dev
  application:
    name: mldncloud-config-client  # 定义微服务名称

---
server:
  port: 8102

spring:
  profiles: product
  application:
    name: mldncloud-config-client
