spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001

spring:
  profiles: dev
  application:
    name: mldncloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/dept8001       # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mysqladmin                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  jpa:                                              # 定义JPA的相关配置
    show-sql: true                                  # 显示执行的SQL语句  

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7002.com:7002/eureka
  instance:
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: mldncloud-dept-service
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

---
server: 
  port: 8001

spring:
  profiles: beta
  application:
    name: mldncloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/dept8001       # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mysqladmin                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  jpa:                                              # 定义JPA的相关配置
    show-sql: true                                  # 显示执行的SQL语句  

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7002.com:7002/eureka
  instance:
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: mldncloud-dept-service
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

