spring:
  profiles:
    active:
      - dev
---
server:
  port: 8101

spring:
  profiles: dev
  application:
    name: mldncloud-config-client  # 定义微服务名称

eureka:
  client:                          # 客户端进行Eureka注册配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: config-client.com # 显示主机名称
    prefer-ip-address: true        # 显示IP地址信息
---
server:
  port: 8102

spring:
  profiles: product
  application:
    name: mldncloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: config-client.com # 显示主机名称
    prefer-ip-address: true        # 显示IP地址信息