spring:
  profiles:
    active:
      - dev
---
server:
  port: 8103

spring:
  profiles: dev
  application:
    name: mldncloud-config-client  # 定义微服务名称

info:
  app.name: mldncloud-dev-2
  company.name: www.mldn.cn
  app.version: version-dev-2.0.0

---
server:
  port: 8102

spring:
  profiles: product
  application:
    name: mldncloud-config-client # 定义微服务名称

info:
  app.name: mldncloud-product-1
  company.name: www.mldn.cn
  app.version: version-product-1.0.0